name: Amplify build

on:
  workflow_dispatch:

jobs:
  update_download_page:
    uses: vyos/community.vyos.net/.github/workflows/main.yml@amplify
    with:
      branch: amplify
    secrets:
        AWS_AMPLIFY_ACCESS_KEY_ID: ${{ secrets.AWS_AMPLIFY_ACCESS_KEY_ID }}
        AWS_AMPLIFY_SECRET_ACCESS_KEY: ${{ secrets.AWS_AMPLIFY_SECRET_ACCESS_KEY }}