name: Amplify build

on:
  workflow_dispatch:

jobs:
  update_download_page:
    uses: vyos/community.vyos.net/.github/workflows/main.yml@amplify
    with:
      branch: amplify
      aws_amplify_region: ${{ vars.AWS_AMPLIFY_REGION }}
      aws_amplify_app_id: ${{ vars.AWS_AMPLIFY_APP_ID }}
    secrets:
        AWS_AMPLIFY_ACCESS_KEY_ID: ${{ secrets.AWS_AMPLIFY_ACCESS_KEY_ID }}
        AWS_AMPLIFY_SECRET_ACCESS_KEY: ${{ secrets.AWS_AMPLIFY_SECRET_ACCESS_KEY }}